config/routes.rb
Vruby::Application.routes.draw do
  resources :instruction_templates

  resources :instruction_sets

  resources :instructions

  resources :schmattas

  resources :web_pages

  match 'instruction_sets/:id' => 'instruction_sets#execute'

  root :to => 'instruction_sets#index'

end

app/models/instruction.rb
class Instruction

  include DataMapper::Resource

  property :id, Serial
  property :name, String

  property :code, Text
  property :ordering, Integer
 
  belongs_to :instruction_template

  belongs_to :instruction_set

  def initialize ()
    
   
  end

  def configure (params, set_id)
    @instruction_template = InstructionTemplate.first(:id => params[:instruction_type][:template_id])
    @instruction_template.instructions << self
    self.name = @instruction_template.name
    @instruction_set = InstructionSet.first(:id => set_id)
    @instruction_set.instructions << self

  end

end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  # GET /instructions
  # GET /instructions.json


  def index
    @instructions = Instruction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instructions }
    end
  end

  # GET /instructions/1
  # GET /instructions/1.json
  def show
    @instruction = Instruction.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instruction }
    end
  end

  # GET /instructions/new
  # GET /instructions/new.json
  def new 
    @instruction = Instruction.new
    session[:set_id] = params[:set_id]

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instruction }
    end
  end

  # GET /instructions/1/edit
  def edit
    @instruction = Instruction.get(params[:id])
    @set = InstructionSet.first(:id => session[:set_id])
  end

  # POST /instructions
  # POST /instructions.json
  def create
    @instruction = Instruction.new
    @instruction.configure(params, session[:set_id])

    #display the full set of instructions
    @current_instructions_list = Instruction.all(:instruction_set_id => session[:set_id])
    @instruction_set = InstructionSet.first(:id => session[:set_id])
    respond_to do |format|
      if @instruction.save
        format.html { redirect_to :controller => 'instruction_sets', :action => 'show', :id => session[:set_id], notice: 'Instruction was successfully created.' }
        format.json { render json: @instruction, status: :created, location: @instruction }
      else

        format.html { render action: "new" }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instructions/1
  # PUT /instructions/1.json
  def update
    #update the instruction record with any form changes
    @instruction = Instruction.first(:id => params[:id])
    instruction_type_id = params[:instruction_type][:template_id]
    @instruction.instruction_template_id = instruction_type_id
    @instruction.name = InstructionTemplate.first(:id => instruction_type_id).name
    @instruction.save #to avoid a "dirty" raise...seems sloppy

    #prepare to show the current set and its associated instructions. DRY this
    @current_instructions_list = Instruction.all(:instruction_set_id => session[:set_id])
    @instruction_set = InstructionSet.first(:id => session[:set_id])

    respond_to do |format|
      if @instruction.update(params[:instruction])
        format.html { redirect_to :controller => 'instruction_sets', :action => 'show', :id => session[:set_id], notice: 'Instruction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instruction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructions/1
  # DELETE /instructions/1.json
  def destroy
    @instruction = Instruction.get(params[:id])
    @instruction.destroy

    respond_to do |format|
      format.html { redirect_to instructions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/views/instructions/_form.html.erb
<%= form_for(@instruction) do |f| %>
  <% if @instruction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction.errors.count, "error") %> prohibited this instruction from being saved:</h2>

      <ul>
      <% @instruction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

Select Instruction
  <%= collection_select(:instruction_type, :template_id, InstructionTemplate.all, :id, :name) %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_area :code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructions/edit.html.erb
<h1>Editing instruction</h1>

<%= render 'form' %>

<%= link_to 'Show', @instruction %> |
<%= link_to 'Back', instructions_path %>

app/views/instructions/index.html.erb
<h1>Listing Instructions</h1>

<table>
 

<% @instructions.each do |instruction| %>
  <tr>
    <td><%= instruction.name %></td>
    <td><%= link_to 'Show', instruction %></td>
    <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
    <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instruction', new_instruction_path %>

app/views/instructions/new.html.erb
<h1>New Instruction</h1>

<%= render 'form' %>

<%= link_to 'Back', instructions_path %>

app/views/instructions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @instruction.name %>
</p>


<%= link_to 'Edit', edit_instruction_path(@instruction) %> |
<%= link_to 'Back', instructions_path %>