config/routes.rb
Vruby::Application.routes.draw do
  resources :instruction_templates

  resources :instruction_sets

  resources :instructions

  resources :schmattas

  resources :web_pages

  match 'instruction_sets/:id' => 'instruction_sets#execute'

  root :to => 'instruction_sets#index'

end

app/models/instruction_set.rb
class InstructionSet

  include DataMapper::Resource

  property :name, String
  property :id, Serial

  has n, :instructions  




end

app/controllers/instruction_sets_controller.rb
class InstructionSetsController < ApplicationController
  # GET /instruction_sets
  # GET /instruction_sets.json
  def index
    @instruction_sets = InstructionSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instruction_sets }
    end
  end

  # GET /instruction_sets/1
  # GET /instruction_sets/1.json
  def show
    @instruction_set = InstructionSet.first(:id => params[:id])
    @current_instructions_list = @instruction_set.instructions.all 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instruction_set }
    end
  end

  # GET /instruction_sets/new
  # GET /instruction_sets/new.json
  def new
    @instruction_set = InstructionSet.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instruction_set }
    end
  end

  # GET /instruction_sets/1/edit
  def edit
    @instruction_set = InstructionSet.get(params[:id])
    session[:set_id] = params[:id]
  end

  def execute
    @instruction_set = InstructionSet.get(params[:id])
    @instruction_set.each do |instruction| 
    template = InstructionTemplate.first[:id => instruction.template_id]
    end
  end

  # POST /instruction_sets
  # POST /instruction_sets.json
  def create
    @instruction_set = InstructionSet.new(params[:instruction_set])


    respond_to do |format|
      if @instruction_set.save
        session[:set_id] = @instruction_set.id
        format.html { redirect_to @instruction_set, notice: 'Instruction set was successfully created.' }
        format.json { render json: @instruction_set, status: :created, location: @instruction_set }
      else
        format.html { render action: "new" }
        format.json { render json: @instruction_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instruction_sets/1
  # PUT /instruction_sets/1.json
  def update
    @instruction_set = InstructionSet.get(params[:id])

    respond_to do |format|
      if @instruction_set.update(params[:instruction_set])
        format.html { redirect_to @instruction_set, notice: 'Instruction set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instruction_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruction_sets/1
  # DELETE /instruction_sets/1.json
  def destroy
    @instruction_set = InstructionSet.get(params[:id])
    @instruction_set.destroy

    respond_to do |format|
      format.html { redirect_to instruction_sets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instruction_sets_helper.rb
module InstructionSetsHelper
end

app/views/instruction_sets/_form.html.erb
<%= form_for(@instruction_set) do |f| %>
  <% if @instruction_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction_set.errors.count, "error") %> prohibited this instruction_set from being saved:</h2>

      <ul>
      <% @instruction_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruction_sets/edit.html.erb
<h1>Editing instruction_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @instruction_set %> |
<%= link_to 'Back', instruction_sets_path %>

app/views/instruction_sets/index.html.erb
<h1>Listing instruction_sets</h1>

<table>

<% @instruction_sets.each do |instruction_set| %>
  <tr>
    <td><%= instruction_set.name %></td>
    <td><%= link_to 'Show', instruction_set %></td>
    <td><%= link_to 'Edit', edit_instruction_set_path(instruction_set) %></td>
    <td><%= link_to 'Destroy', instruction_set, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= link_to 'Execute', instruction_set, method: :execute %> </td> 
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instruction set', new_instruction_set_path %><br />
<%= link_to 'TEST New Webpage', new_web_page_path %> <br />
<%= link_to 'Show Instruction Templates', instruction_templates_path %> <br />

app/views/instruction_sets/new.html.erb
<h1>New instruction_set</h1>

<%= render 'form' %>

<%= link_to 'Back', instruction_sets_path %>

app/views/instruction_sets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @instruction_set.name%>
</p>

<table>
<% @current_instructions_list.each do |instruction| %>
  <tr>
    <td><%= instruction.name %></td>
    <td><%= link_to 'Show', instruction %></td>
    <td><%= link_to 'Edit', edit_instruction_path(instruction) %></td>
    <td><%= link_to 'Destroy', instruction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Execute Instruction Set', @instruction_set, method: :execute %>

<%= link_to 'New Instruction', new_instruction_path(:set_id => params[:id])%>

<%= link_to 'Edit', edit_instruction_set_path(params[:id]) %> |
<%= link_to 'Back', instruction_sets_path %>