config/routes.rb
Vruby::Application.routes.draw do
  resources :instruction_templates

  resources :instruction_sets

  resources :instructions

  resources :schmattas

  resources :web_pages

  match 'instruction_sets/:id' => 'instruction_sets#execute'

  root :to => 'instruction_sets#index'

end

app/models/schmatta.rb
class Schmatta

  include DataMapper::Resource

  property :id, Serial

  property :name, String
  property :description, Text

  #has 1, :instruction

end

app/controllers/schmattas_controller.rb
class SchmattasController < ApplicationController
  # GET /schmattas
  # GET /schmattas.json
  def index
    @schmattas = Schmatta.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @schmattas }
    end
  end

  # GET /schmattas/1
  # GET /schmattas/1.json
  def show
    @schmatta = Schmatta.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schmatta }
    end
  end

  # GET /schmattas/new
  # GET /schmattas/new.json
  def new
    @schmatta = Schmatta.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @schmatta }
    end
  end

  # GET /schmattas/1/edit
  def edit
    @schmatta = Schmatta.get(params[:id])
  end

  # POST /schmattas
  # POST /schmattas.json
  def create
    @schmatta = Schmatta.new(params[:schmatta])

    respond_to do |format|
      if @schmatta.save
        format.html { redirect_to @schmatta, notice: 'Schmatta was successfully created.' }
        format.json { render json: @schmatta, status: :created, location: @schmatta }
      else
        format.html { render action: "new" }
        format.json { render json: @schmatta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /schmattas/1
  # PUT /schmattas/1.json
  def update
    @schmatta = Schmatta.get(params[:id])

    respond_to do |format|
      if @schmatta.update(params[:schmatta])
        format.html { redirect_to @schmatta, notice: 'Schmatta was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schmatta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schmattas/1
  # DELETE /schmattas/1.json
  def destroy
    @schmatta = Schmatta.get(params[:id])
    @schmatta.destroy

    respond_to do |format|
      format.html { redirect_to schmattas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/schmattas_helper.rb
module SchmattasHelper
end

app/views/schmattas/_form.html.erb
<%= form_for(@schmatta) do |f| %>
  <% if @schmatta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schmatta.errors.count, "error") %> prohibited this schmatta from being saved:</h2>

      <ul>
      <% @schmatta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schmattas/edit.html.erb
<h1>Editing schmatta</h1>

<%= render 'form' %>

<%= link_to 'Show', @schmatta %> |
<%= link_to 'Back', schmattas_path %>

app/views/schmattas/index.html.erb
<h1>Listing schmattas</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @schmattas.each do |schmatta| %>
  <tr>
    <td><%= schmatta.name %></td>
    <td><%= link_to 'Show', schmatta %></td>
    <td><%= link_to 'Edit', edit_schmatta_path(schmatta) %></td>
    <td><%= link_to 'Destroy', schmatta, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Schmatta', new_schmatta_path %>

app/views/schmattas/new.html.erb
<h1>New schmatta</h1>

<%= render 'form' %>

<%= link_to 'Back', schmattas_path %>

app/views/schmattas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @schmatta.name %>
</p>


<%= link_to 'Edit', edit_schmatta_path(@schmatta) %> |
<%= link_to 'Back', schmattas_path %>