config/routes.rb
Vruby::Application.routes.draw do
  resources :instruction_templates

  resources :instruction_sets

  resources :instructions

  resources :schmattas

  resources :web_pages

  match 'instruction_sets/:id' => 'instruction_sets#execute'

  root :to => 'instruction_sets#index'

end

app/models/instruction_template.rb
class InstructionTemplate

  include DataMapper::Resource

  property :id, Serial
  property :name, String

  has n, :instructions

  def execute
#store execution code in separate yaml or ruby files? Yes, as fixture, but load them in.
#could make it hard to debug.
#for now, create a single file of executions and mix them in to this template?

#case statement here? 

		execute_create_web_page
  end

  def execute_create_web_page
  	raise ("error creating web page") unless my_page = WebPage.new 
  	return my_page
  end

end

app/controllers/instruction_templates_controller.rb
class InstructionTemplatesController < ApplicationController
  # GET /instruction_templates
  # GET /instruction_templates.json
  def index
    @instruction_templates = InstructionTemplate.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instruction_templates }
    end
  end

  # GET /instruction_templates/1
  # GET /instruction_templates/1.json
  def show
    @instruction_template = InstructionTemplate.get(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instruction_template }
    end
  end

  # GET /instruction_templates/new
  # GET /instruction_templates/new.json
  def new
    @instruction_template = InstructionTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instruction_template }
    end
  end

  # GET /instruction_templates/1/edit
  def edit
    @instruction_template = InstructionTemplate.get(params[:id])
  end

  # POST /instruction_templates
  # POST /instruction_templates.json
  def create
    @instruction_template = InstructionTemplate.new(params[:instruction_template])

    respond_to do |format|
      if @instruction_template.save
        format.html { redirect_to @instruction_template, notice: 'Instruction template was successfully created.' }
        format.json { render json: @instruction_template, status: :created, location: @instruction_template }
      else
        format.html { render action: "new" }
        format.json { render json: @instruction_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instruction_templates/1
  # PUT /instruction_templates/1.json
  def update
    @instruction_template = InstructionTemplate.get(params[:id])

    respond_to do |format|
      if @instruction_template.update(params[:instruction_template])
        format.html { redirect_to @instruction_template, notice: 'Instruction template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instruction_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruction_templates/1
  # DELETE /instruction_templates/1.json
  def destroy
    @instruction_template = InstructionTemplate.get(params[:id])
    @instruction_template.destroy

    respond_to do |format|
      format.html { redirect_to instruction_templates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instruction_templates_helper.rb
module InstructionTemplatesHelper
end

app/views/instruction_templates/_form.html.erb
<%= form_for(@instruction_template) do |f| %>
  <% if @instruction_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instruction_template.errors.count, "error") %> prohibited this instruction_template from being saved:</h2>

      <ul>
      <% @instruction_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruction_templates/edit.html.erb
<h1>Editing instruction_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @instruction_template %> |
<%= link_to 'Back', instruction_templates_path %>

app/views/instruction_templates/index.html.erb
<h1>Listing instruction_templates</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instruction_templates.each do |instruction_template| %>
  <tr>
    <td><%= instruction_template.name %></td>
    <td><%= link_to 'Show', instruction_template %></td>
    <td><%= link_to 'Edit', edit_instruction_template_path(instruction_template) %></td>
    <td><%= link_to 'Destroy', instruction_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instruction template', new_instruction_template_path %>

app/views/instruction_templates/new.html.erb
<h1>New instruction_template</h1>

<%= render 'form' %>

<%= link_to 'Back', instruction_templates_path %>

app/views/instruction_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @instruction_template.name %>
</p>


<%= link_to 'Edit', edit_instruction_template_path(@instruction_template) %> |
<%= link_to 'Back', instruction_templates_path %>